services:
  frontend:
    # ...existing code...
    environment:
      - VITE_API_URL=http://backend:8000/api/v1
      - VITE_WS_URL=ws://backend:8000/ws
    # ...existing code...
# ...existing code...